
language: minimal
services:
  - docker
script:
  - docker build --no-cache --pull -t quay.io/wisvch/flitcie-gallery3:$TRAVIS_BUILD_NUMBER .
deploy:
  provider: script
  script: >-
    sh -c '
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/wisvch/flitcie-gallery3:$TRAVIS_BUILD_NUMBER;
    '
  on:
    branch: master
notifications:
  email: false
